### ISSUE TITLE
[request] Ensure AP name does not conflict

### ISSUE THREAD

**Issue by jminardi** [foosel/netconnectd#10]
Would it be possible to ensure the AP name does not conflict with any WiFi networks in range?

**Comment by foosel** [comment]
Technically possible: yes.

But it would require some larger code changes, since the hostapd configuration file would have to be rewritten basically on every start of the AP after performing an initial site survey.

The question is if it wouldn't be easier to just chose an AP name with very little likelihood of colliding. Example: Have the daemon be started with a dynamically set ap name based on e.g. a serial number of the host running the daemon.

**Comment by jminardi** [comment]
Makes sense, that was my plan if this idea was too difficult. Closing as not likely to implement.
